apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: artemis-gulmira
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.endpoint }}
  - http:
      paths:
      - path: /
        backend:
          serviceName: artemis-gulmira
          servicePort: 80
  tls:
  - hosts:
    - {{ .Values.endpoint }}
    secretName: dashboard-proxy-tls