---
- name: Install and Configure Fail2ban
  hosts: localhost
  tasks:
    - name: Install epel-release repository on CentOS7
      when: ansible_distribution == "CentOS"
      yum:
        name: epel-release
        state: present




    - name: Install Fail2ban
      yum:
        name: fail2ban
        state: present


    - name: Enable Fail2ban service
      service:
        name: fail2ban
        enabled: yes


    - name: Create configuration file (jail.local) file on Centos7
      when: ansible_distribution == "CentOS"
      file:
        path: /etc/fail2ban/jail.local
        state: touch


    - name: Update Configuration file on Centos7
      when: ansible_distribution == "CentOS"
      blockinfile:
        path: /etc/fail2ban/jail.local
        block: |
          [DEFAULT]
          banaction = iptables-multiport
          ignoreip = 50.194.68.230/32            #Enter the ip IP/CIDR block to bei
          bantime = 3600
          findtime = 120
          maxretry = 3
          [sshd]
          enabled  = true
          
          
          
    - name: Restart Fail2ban service on Centos7
      when: ansible_distribution == "CentOS"
      systemd:
        name: fail2ban
        state: restarted
