apiVersion: v1
version: 1.10.1
name: artemis-umar
appVersion: 1.10.1
description: this is a test chart for artemis
maintainers:
- name: LmStripe
- email: lazizmansurov4@gmail.com
home: https://github.com/Evolve-Cyber-Organization/Acirrustech-Env.git
sources:
- https://github.com/Evolve-Cyber-Organization/Acirrustech-Env.git