apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: merve-artemis
  # annotations:
   # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.endpoint }}
  - http:
      paths:
      - path: /
        # pathType: Prefix
        backend:
          serviceName: merve-artemis
          servicePort: 80
